### ISSUE TITLE
Various layout issue on 2016 iPhone SE

### ISSUE THREAD

**Issue by tyrann0us** [openopus-org/concertino_ios#8]
On my 2016 iPhone SE, I see the following layout issues:
1. The top of the library view is clipped; the "Most Requested Composers" title is moved outside the viewport, you have to "overscroll" to see it
2. Contrary to the screenshots in the App Store, the "Search" view does not show any kind of actual search input
3. The "Favorites" view is also clipped; no way to overscroll
4. The controls in the currently playing overlay don't have paddings on left and right

Please see a screencast of all mentioned issues here (I had to zip the `mp4` because GitHub won't allow videos): [RPReplay_Final1598087050.MP4.zip](https://github.com/openopus-org/concertino_ios/files/5121705/RPReplay_Final1598087050.MP4.zip)

* iPhone SE (2016, 1. Generation)
* iOS 14 Beta 5 (18A5351d)
* Concertino 1.20.817

**Comment by adrianosbr** [comment]
Hi Philipp,

Thank you so much for the feedback.

Those issues are all related to the way iOS 14 deals with SwiftUI
navigation. It's working fine on larger screens (my iOS 14 device is an
iPhone XS Max; my other test devices are all running iOS 13), but seems to
break on smaller devices (and the original iPhone SE is the smallest iOS
13/14 compatible device).

On iOS 13, it's quite crammed but works:

[image: Simulator Screen Shot - iPhone SE (1st generation) - 2020-08-25 at
20.54.24.png]
[image: Simulator Screen Shot - iPhone SE (1st generation) - 2020-08-25 at
20.50.26.png]

(I can't test the app very well on the simulator because MusicKit isn't
available on simulators. I don't have an iPhone SE. My smallest test device
is an iPhone 8.)

I'll compile an iOS 14-specific version on Xcode 12 beta and make the
TestFlight link available here.

Cheers,
Adriano.

**Comment by adrianosbr** [comment]
Hi Philipp,

Thank you so much for the feedback.

Those issues are all related to the way iOS 14 deals with SwiftUI navigation. It's working fine on larger screens (my iOS 14 device is an iPhone XS Max; my other test devices are all running iOS 13), but seems to break on smaller devices (and the original iPhone SE is the smallest iOS 13/14 compatible device).

On iOS 13, it's quite crammed but works:

![Simulator Screen Shot - iPhone SE (1st generation) - 2020-08-25 at 20 54 24](https://user-images.githubusercontent.com/6960072/91239573-4cae2780-e716-11ea-99ca-79b0b60bdbc2.png)
![Simulator Screen Shot - iPhone SE (1st generation) - 2020-08-25 at 20 50 26](https://user-images.githubusercontent.com/6960072/91239576-4e77eb00-e716-11ea-8db3-cb0348488600.png)

(I can't test the app very well on the simulator because MusicKit isn't available on simulators. I don't have an iPhone SE. My smallest test device is an iPhone 8.)

I'll compile an iOS 14-specific version on Xcode 12 beta and make the TestFlight link available here.

Cheers,
Adriano.

**Comment by adrianosbr** [comment]
Bugs fixed, beta version already submitted to Apple.

When it becomes available on TestFlight, I'll post the link here.

Thanks! :)

**Comment by adrianosbr** [comment]
Apple was really fast and the release is available on TestFlight:

https://testflight.apple.com/join/IXgVtBwW

**Comment by tyrann0us** [comment]
Hi @adrianosbr, thanks for your fast response! Unfortunately, I see no difference at all; all mentioned issues still persist.
Please see the attached screencast: [RPReplay_Final1598510377.mov.zip](https://github.com/openopus-org/concertino_ios/files/5134524/RPReplay_Final1598510377.mov.zip)

**Comment by adrianosbr** [comment]
Hi @tyrann0us! I think you've downloaded the old version. I forgot to click a tiny button on AppStore Connect to "notify testers", which effectively make the new version available for testing. Now it's done. Sorry for that :)

**Comment by tyrann0us** [comment]
Yep, I just got a notification. Updated the app and it’s working like a charm!
Thanks!

**Comment by adrianosbr** [comment]
Great to hear! I plan to make those fixes publicly available when our next features - album view and devices sync - get ready. So it may take three or four weeks.
